### ISSUE TITLE
CRITICAL : no filter named 'sidebar'

### ISSUE THREAD

**Issue by Yannovitch** [frankV/twenty-pelican-html5up#1]
Hello,

After having added your theme to my configuration file, when I try to do "pelican content", I have an error CRITICAL : no filter named 'sidebar'.

Could you help me solve it please ?
Thanks,
Y

**Comment by m8ttyB** [comment]
@Yannovitch Sorry for the confusion .. that branch is _still in active development_ and doesn't compile. I've recently been doing some explorations with bootstrap and will likely abandon this branch and go in a different direction.

I'm still undecided though. I do know that I it's time to do a site redesign and update. 

The error your seeing is related to the `sidebar filter` not being implemented. I never got around to doing that work.

**Comment by frankV** [comment]
create a `utils` module in the same directory as your `pelicanconf.py` file. Add this to a file named `filters.py`

``` python
def sidebar(value):
  if value.startswith('archives') or value.startswith('category'):
    return 'right-sidebar'
  elif value == 'index':
    return 'index'
  else:
    return 'no-sidebar'
```

Then import it into `pelicanconf.py` and define the `JINJA_FILTERS` <-- this is a pelican convention.

``` python
from utils import filters
JINJA_FILTERS = { 'sidebar': filters.sidebar }
```

**Comment by frankV** [comment]
Should be good now.
https://github.com/frankV/twenty-pelican-html5up/commit/53cc173993b358690e8ea00de02154547d5dfdca

**Comment by macskay** [comment]
i still get that error

**Comment by koobs** [comment]
@mkli90 Create an empty file in the utils/ directory called __init__.py

**Comment by bobrocksgithub** [comment]
That makes 2 of us... :face_with_head_bandage:

**Comment by frankV** [comment]
@mkli90 @bobrocksgithub can you guys do a tree of your project directory? And maybe confirm what you have in your utils/filters.py

**Comment by bobrocksgithub** [comment]
thanks for responding @frankV 
I think the issue is probably on this side of the keyboard, so I'm really glad to have your help.

my project tree contains folders: 
`content
env
output
plugins
utils`

and files: 
`develop_server.sh
fabfile.py
Makefile
pelicanconf.py
pelicanconf.pyc
publishconf.py`

in project/utils/filters.py:
`def sidebar(value):
  if value.startswith('archives') or value.startswith('category'):
    return 'right-sidebar'
  elif value == 'index':
    return 'index'
  else:
    return 'no-sidebar'`

**Comment by frankV** [comment]
@bobrocksgithub compare your project structure to mine here: https://bitbucket.org/frankv/frankvalcarcel.com/src

This repository is just for the template, so it doesn't make sense to have a full Pelican project here.

If you're getting a `no filter named 'sidebar'` error it's got something to do with either how you're importing it, or your Jinja enviroment. That's my best guess.

Forgive me for asking this, but do you have an `__init__.py` in utils? I'm assuming you do, else you'd likely get an import error. The other box we should check is that you have the actual import statement in `pelicanconf.py` > `from utils import filters`

Lastly, try deleting any `*.pyc` files.

**Comment by bobrocksgithub** [comment]
Thanks for helping @frankV ...
OK, if I comment out the 
`from utils import filters
JINJA_FILTERS = { 'sidebar': filters.sidebar }`
from my pelicanconf.py, then I get the `no filter named 'sidebar'` error.
If I uncomment those lines, I get this error:
`File "pelicanconf.py", line 38, in <module>
    from utils import filters
ImportError: No module named utils`

Which tells me I am clearly doing something wrong. 
I do not have a `__init__.py` file in utils. If I throw one in there (blank like your bitbucket structure) then I get an error of:
`File "~/local/lib/python2.7/site-packages/pelican/cache.py", line 11, in <module>
    from pelican.utils import mkdir_p
ImportError: cannot import name mkdir_p`

It could absolutely be something to do with my Jinja config, but it is completely vanilla...
I'm creating a virtualenv, setting up pelican and markdown in it, then dropping your `twenty` theme into the `themes` folder, creating a `utils` folder, placing the `filters.py` in there and then modifying the pelicanconf.py with `from utils import filters`...

Thanks again for helping, I really appreciate it.

**Comment by frankV** [comment]
@bobrocksgithub do you have your site up in a repo?

If you clone/download my site from Bitbucket, does it run after installing the requirements?

**Comment by bobrocksgithub** [comment]
Alright @frankV after some messing about, your repo is working for me. 
I'll compare files and see where I fell off the wagon... 
Thanks!

**Comment by frankV** [comment]
Thanks @bobrocksgithub, glad you got to that point. If you find the flaw, please respond here so anyone else that encounters this issue has a possible solution. Obviously the caveat in the README isn't enough.

**Comment by bobrocksgithub** [comment]
Hey @frankV yeah, thanks for your help!
I think where I got into trouble was trying to mix and match the html5up files with your customized files.
I wanted the navbar to display links instead of being collapsed in all cases (as it appears your template is configured to do).
Going to a clean clone of your repo and tweaking according to your `README.md` makes things work great.
Now I get to wade through the new changes to the twenty theme and try to migrate your work to the latest.
Thanks for the head start and help!

**Comment by tjnel** [comment]
This is not working for me also so any information on specifically what you did @bobrocksgithub would be great - i am using py3.5 so fabfiles will not work.

**Comment by AnnaGolubeva** [comment]
I was struggling with the same issue. I've noticed that it won't find any module at all, no matter where I place it. Adding the path to the `pelicanconf.py` solves this!
  `import sys`
  `sys.path.append('.')`

**Comment by val314159** [comment]
I solved this with the following in `pelicanconf.py`

```
import filters
JINJA_FILTERS={ 'sidebar': filters.sidebar }
```

then running `PYTHONPATH=. make clean html serve`

**Comment by bishopb** [comment]
Besides creating `utils/filters.py` and ensuring the local directory is in `PYTHONPATH`, you may also need to create an `__init__.py`:

```
touch utils/__init__.py
```
