### ISSUE TITLE
skel.js

### ISSUE THREAD

**Issue by annemanguyen** [frankV/twenty-pelican-html5up#3]
Hi Frank! Was hoping you could help with solving the skel.js issue. I added the collectstatic script to fabfile.py, but I don't understand how to get it to work, so I still get a bunch of "Unable to find" warnings. This person appears to have the same issue: http://categori.se/blog/setting-up-this-theme/. Do you have any advice? Thanks so much.

**Comment by frankV** [comment]
@amn34 see if you can find an answer here: [https://bitbucket.org/frankv/twenty-pelican-html5up](https://bitbucket.org/frankv/twenty-pelican-html5up)

Can you confirm that your js and css files are under their own directories below `themes/twenty/static/`?

**Comment by ShaunaGordon** [comment]
I'm not totally sure if it's relevant, but I did notice that http://skeljs.org/ is a dead link.

**Comment by frankV** [comment]
Updated the README with the correct link. Seems like @n33 just has it pointing to the repo now. Thanks!
